### ISSUE TITLE
Argument error when trying to parse unicode in JSON

### ISSUE THREAD

**Issue by thepug** [cblage/elixir-json#29]
The parser seems to have issues with some unicode strings.

`iex(8)> JSON.decode("{\"name\": \"Fahad Al-Esmail \\u00f8\"}")
{:ok, %{"name" => "Fahad Al-Esmail ø"}}
iex(9)> JSON.decode("{\"name\": \"Fahad Al-Esmail \\ud83c\"}")
** (ArgumentError) argument error
   lib/json/parser/bitstring/string.ex:85: JSON.Parser.Bitstring.String.parse_escaped_unicode_codepoint/3
   lib/json/parser/bitstring/string.ex:65: JSON.Parser.Bitstring.String.parse_string_contents/2
   lib/json/parser/bitstring/object.ex:50: JSON.Parser.Bitstring.Object.parse_object_value/3
   lib/json/decoder.ex:30: JSON.Decoder.BitString.decode/1
`

**Comment by hectorip** [comment]
So far as I've seen nobody has worked on this, am I right. I need this fixed for my project; I think I will be working on this today.
