### ISSUE TITLE
Struct Support,

### ISSUE THREAD

**Issue by noizu** [cblage/elixir-json#33]
The library doesn't seem to support struct objects out of the gate. They're caught by the Any handler and serialized as something along the lines of [Elixir.Any]

Do you have a recommended best practice or any suggestions on making struct encoding/decoding straight forward. 

I'm pretty new to the language but my initial workaround is to just do the following along with a use JsonStruct in any structures I need to encode. I think this approach could also be used to decode to struct with some additional metaprogramming magic but I have no idea if it's the best solution or if there is already a more straight forward undocumented way to easily decode/encode structs. 

```
defmodule JsonStruct do
  use Behaviour
  defmacro __using__(_opts) do
    quote do
      import unquote(__MODULE__)
      @derive [Enumerable, Access]
      defimpl JSON.Encoder, for: __MODULE__ do
        def encode(dict), do: JSON.Encoder.Helpers.dict_encode(dict)
        def typeof(_), do: :object
      end
    end
  end
end
```

**Comment by cblage** [comment]
Thanks for the report, I'll try to look at this soon ^^

**Comment by cblage** [comment]
@noizu sorry for the delay, but I've just gotten some free time to work on OSS stuff. Would you be willing to open a PR for this or prefer me to work on it? :smile:

**Comment by vandrada** [comment]
I was able to encode structs by using `Map.from_struct` on the struct before it's passed to `dict_encode`. Encoding the struct example from the docs, results in

    {:ok, "{\"age\":27,\"name\":\"John\"}"}

If the `__struct__` key should be kept, using `Map.to_list` results in

    {:ok, "{\"__struct__\":\"Elixir.User\",\"age\":27,\"name\":\"John\"}"}

I'm not sure which one would be better.

**Comment by cblage** [comment]
Not sure either. I'm inclined to  keep the __struct__ key to make it more easily reverse-converted. What do you think?

**Comment by vandrada** [comment]
That was my initial thought too. I'll go ahead and open a PR

**Comment by cblage** [comment]
Any news @vandrada ?

**Comment by cblage** [comment]
I'll try to implement this myself soon :)

**Comment by vandrada** [comment]
Sorry for the delay, but I thought this was merged with https://github.com/cblage/elixir-json/commit/131809bf35d435c504d430609f3dd9898e39e04a

**Comment by cblage** [comment]
DOH. Seems like I forgot to close the issue xD 

![homerback](https://cloud.githubusercontent.com/assets/939776/12665930/b7a189b6-c609-11e5-8616-e5935948875d.gif)

**Comment by cblage** [comment]
BTW, @vandrada - mind taking a look at this? https://github.com/cblage/elixir-json/issues/38

**Comment by cblage** [comment]
It's not an issue, just a discussion about the future of the project
