### ISSUE TITLE
[META] Moving this project to an organization to give community control over it

### ISSUE THREAD

**Issue by cblage** [cblage/elixir-json#38]
I would like to hear opinions about this, especially from people who contributed to the project.

I'm currently strongly considering "donating" the project to the community and put it under an organization (current tentative name: https://github.com/open-elixir).

Any opinions on the subject would be appreciated, I would still be contributing to the project as much as possible and reviewing pull requests, but I feel that a JSON library should not "belong" to any given user.

Thoughts?

cc: @josevalim, @ericmj, @hectorip, @jamesarosen, @vandrada, @parroty, @falood, @herenowcoder, @lsimoneau, @herenowcoder, @kalloc, @mathieul, @pminten, @patrickdet, @pauldipietro, @lowks

**Comment by lowks** [comment]
Agree.



[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

**Comment by vandrada** [comment]
I think it's a good idea to donate this project to the community at large

**Comment by jamesarosen** [comment]
My vote is worth very little here, but strong +1.

**Comment by kalloc** [comment]
It is a good idea!

**Comment by herenowcoder** [comment]
I think there's nothing wrong with having an important library tied to someone's name, but having said that - do it as it makes you feel fine..

cheers

**Comment by Havvy** [comment]
Get at least two other important Elixir projects to join you initially so that it's actually a community of projects and not just the elixir-json community initially.

Also, try to have defined policy around controversial changes.

**Comment by cblage** [comment]
I intend on adding a few more projects of my own (yet to be released) to the org and hope more will join.

Controversial changes will be discussed through RFC-style decision making process.

**Comment by cblage** [comment]
This is the new tentative organization where I would like to start with: https://github.com/wehacktogether

Any objections / ideas? :fire:

**Comment by cblage** [comment]
The process is underway. Will try to have this moved to the new org soon :).

**Comment by cblage** [comment]
Also, I'm open to new names suggestions. I was trying to follow the "Node.js module" naming convention, but I guess that's not really the spirit of the Elixir community. 

Current ideas:
- **jsonator**
- **bacon-json**
- **bacon**
- **baconator**
- **dr-json**

I'm also open to suggestions :)

cc: @josevalim, @ericmj, @hectorip, @jamesarosen, @vandrada, @parroty, @falood, @herenowcoder, @lsimoneau, @herenowcoder, @kalloc, @mathieul, @pminten, @patrickdet, @pauldipietro, @lowks

**Comment by vandrada** [comment]
+1 for jsonator

**Comment by herenowcoder** [comment]
3 cents, 

I think it's a bit late for changing the app name (in terms of `mix`). Everybody who has it in his `mix.exs` would need to change. It's somewhat [popular](https://hex.pm/packages/json) already.

Then if you want to change only the github name, `elixir-json` is still one name most closely corresponding to the app name.

**Comment by Havvy** [comment]
It's not too late. Old packages would use the old name and new packages would use the new name. There's a risk of having two versions installed, but for something like this, that's mostly a non-issue.

I would stay away from calling anything "bacon" in the tech world. I see it used often enough as it is.

All that said, I don't have a strong opinion one way or the other on what you decide.

**Comment by josevalim** [comment]
One question worth asking is what is the differences between this project and Poison? If there are not enough differences, wouldn't it be preferable to retire this package an unify the efforts towards Poison? I am mentioning Poison because it is the one recommended by Ecto, Phoenix, etc.

**Comment by cblage** [comment]
I have decided against changing the name of the library, but still looking forward moving to an organization. 

@josevalim the differences are mainly in the code style as far as I can tell (although Poison has a certain performance advantage atm). I would only consider deprecating this if we were to create a community-centered org for these kind of libraries (json, jwt tokens, msgpack, etc) and have them be pure community-organized projects.

**Comment by ericmj** [comment]
@cblage Can you explain why Poison being community organized would be a benefit over the current ownership and why this should prevent deprecating Json over Poison? And you can explain a bit more in detail the ownership structure of community organized projects that you have in mind; for example who owns the Hex package, who is admin for the github organization and who has the authority to make final decisions for a project when the community does not agree?

I generally think if we have multiple packages doing the same thing efforts should try be combined into a single package to reduce duplicate work. It would be a shame if we couldn't combine Json and Poison because the requirement of Poison being community organized. Maybe you could ask @devinus to add you as a contributor on Poison and be part of the decision making for the project?

**Comment by cblage** [comment]
@ericmj I'm trying to encourage other developers to follow suit with something like https://github.com/kohana/kohana for the community model. 
Who would run it? The original authors of any lib that joins, and any member of the community who would like to dedicate time to it.

/cc: @shadowhand @josevalim

**Comment by shadowhand** [comment]
I am strongly of the opinion that all open source projects should be attributed to an organization rather than a single developer. So :+1: for following a community model.

Also very happy to see that @cblage is being thoughtful about this move and soliciting feedback. I am excited to see valuable open source projects taking this approach.

**Comment by cblage** [comment]
closing this as the final decision went towards not breaking repos / dependencies and keeping the current project uri
