### ISSUE TITLE
Comparison with Poison

### ISSUE THREAD

**Issue by benwilson512** [cblage/elixir-json#40]
Hey, could you provide a comparison with Poison? It clearly has a lot more momentum, why might I use this library instead?

Thanks!

**Comment by cblage** [comment]
Any opinion I could share would be biased as you might imagine. Why don't you try them both out and share your thoughts? :smile:

**Comment by cblage** [comment]
@benwilson512 gonna close this on a note, Poison is currently faster in raw performance benchmarks (not by any significant production-affecting margin), but I believe Elixir JSON 1.0 has much better documentation: https://hexdocs.pm/json/api-reference.html vs https://hexdocs.pm/poison/api-reference.html
